name: FitInfinite
favicon: null
layout_spectrum: 0.9020852721296251
typography_spectrum: 0.6978598341811448
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4017984971869737
  lightness: 0.5456360878888518
  saturation: 0.7072816709987819
  rhythmicContrast: 0.32540202396921813
purpose: []
