name: FitInfinite
favicon: null
layout_spectrum: 0.9020852721296251
typography_spectrum: 0.6978598341811448
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-62111840-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc6a4a'
    - '#606060'
    - '#ffffff'
    - '#fd9982'
    - '#fdbdae'
  brandStrength: 0.4017984971869737
  lightness: 0.625
  saturation: 0.7072816709987819
  rhythmicContrast: 0.32540202396921813
purpose: []
